server:
  port: ${PORT:8000}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}

  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:schema-postgresql.sql